meta:
  package: objects
  imports:
    - time
    - "github.com/google/uuid"

models:
  - name: message
    fields:
      - name: sendingApp
        type: string
        tag: MSH.3
      - name: sendingFacility
        type: string
        tag: MSH.4
      - name: sentAt
        type: timestamp
        tag: MSH.7
      - name: messageType
        type: CM_MSH
        tag: MSH.9
      - name: controlID
        type: string
        tag: MSH.10
      - name: processingID
        type: string
        tag: MSH.11
      - name: versionID
        type: string
        tag: MSH.12
  - name: patient
    fields:
      - name: mrn
        type: CX
        tag: PID.3
      - name: name
        type: XPN
        tag: PID.5
      - name: dob
        type: timestamp
        tag: PID.7
      - name: sex
        type: string
        tag: PID.8
      - name: address
        type: XAD
        tag: PID.11

types:
  - name: CM_MSH
    fields:
      - name: messageType
      - name: triggerEvent
  - name: CX
    fields:
      - name: id
      - name: checkDigit
      - name: checkDigitScheme
      - name: assigningAuthority
      - name: identifierTypeCode
      - name: assigningFacility
  - name: XPN
    fields:
      - name: lastName
      - name: firstName
      - name: middleName
      - name: suffix
      - name: prefix
      - name: degree
      - name: nameTypeCode
  - name: XAD
    fields:
      - name: streetAddress
      - name: otherDesignation
      - name: city
      - name: state
      - name: zip
      - name: country
      - name: addressType